const CONFIG = {
    introTitle: 'Êuu thằng lồn :))',
    introDesc: `iu em hongg🥺`,
    btnIntro: '🥺🥺',
    title: 'mày mà thoát ra là coi chừng tao đấy😏',
    desc: 'Anh có iu em nhiều hongggg🥺',
    btnYes: 'Yêu nhiều lắm luôn🤤',
    btnNo: 'không =)))',
    question:'Vì sao anh lại yêu em :D?',
    btnReply: 'Gửi cho em nè',
    reply: 'Vì em là em bé của mình anh thoiiii❤️',
    mess: 'tao biết mà😏',
    messDesc: 'vậy thì bớt ib cho gái lại đi:))',
    btnAccept: 'vâng. Yêu emmmmmmm❤️',
    messLink:'https://www.facebook.com/messages/t/100050136552417'
